server:
  port: 8228

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: hello
          uri: http://127.0.0.1:8229
          predicates:
            - Path=/default/**
          filters:
            - StripPrefix=1